require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HospedagensController do

  # This should return the minimal set of attributes required to create a valid
  # Hospedagem. As you add validations to Hospedagem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "dataEntrada" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HospedagensController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all hospedagens as @hospedagens" do
      hospedagem = Hospedagem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hospedagens).should eq([hospedagem])
    end
  end

  describe "GET show" do
    it "assigns the requested hospedagem as @hospedagem" do
      hospedagem = Hospedagem.create! valid_attributes
      get :show, {:id => hospedagem.to_param}, valid_session
      assigns(:hospedagem).should eq(hospedagem)
    end
  end

  describe "GET new" do
    it "assigns a new hospedagem as @hospedagem" do
      get :new, {}, valid_session
      assigns(:hospedagem).should be_a_new(Hospedagem)
    end
  end

  describe "GET edit" do
    it "assigns the requested hospedagem as @hospedagem" do
      hospedagem = Hospedagem.create! valid_attributes
      get :edit, {:id => hospedagem.to_param}, valid_session
      assigns(:hospedagem).should eq(hospedagem)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hospedagem" do
        expect {
          post :create, {:hospedagem => valid_attributes}, valid_session
        }.to change(Hospedagem, :count).by(1)
      end

      it "assigns a newly created hospedagem as @hospedagem" do
        post :create, {:hospedagem => valid_attributes}, valid_session
        assigns(:hospedagem).should be_a(Hospedagem)
        assigns(:hospedagem).should be_persisted
      end

      it "redirects to the created hospedagem" do
        post :create, {:hospedagem => valid_attributes}, valid_session
        response.should redirect_to(Hospedagem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hospedagem as @hospedagem" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hospedagem.any_instance.stub(:save).and_return(false)
        post :create, {:hospedagem => { "dataEntrada" => "invalid value" }}, valid_session
        assigns(:hospedagem).should be_a_new(Hospedagem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hospedagem.any_instance.stub(:save).and_return(false)
        post :create, {:hospedagem => { "dataEntrada" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hospedagem" do
        hospedagem = Hospedagem.create! valid_attributes
        # Assuming there are no other hospedagens in the database, this
        # specifies that the Hospedagem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Hospedagem.any_instance.should_receive(:update).with({ "dataEntrada" => "MyString" })
        put :update, {:id => hospedagem.to_param, :hospedagem => { "dataEntrada" => "MyString" }}, valid_session
      end

      it "assigns the requested hospedagem as @hospedagem" do
        hospedagem = Hospedagem.create! valid_attributes
        put :update, {:id => hospedagem.to_param, :hospedagem => valid_attributes}, valid_session
        assigns(:hospedagem).should eq(hospedagem)
      end

      it "redirects to the hospedagem" do
        hospedagem = Hospedagem.create! valid_attributes
        put :update, {:id => hospedagem.to_param, :hospedagem => valid_attributes}, valid_session
        response.should redirect_to(hospedagem)
      end
    end

    describe "with invalid params" do
      it "assigns the hospedagem as @hospedagem" do
        hospedagem = Hospedagem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hospedagem.any_instance.stub(:save).and_return(false)
        put :update, {:id => hospedagem.to_param, :hospedagem => { "dataEntrada" => "invalid value" }}, valid_session
        assigns(:hospedagem).should eq(hospedagem)
      end

      it "re-renders the 'edit' template" do
        hospedagem = Hospedagem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hospedagem.any_instance.stub(:save).and_return(false)
        put :update, {:id => hospedagem.to_param, :hospedagem => { "dataEntrada" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hospedagem" do
      hospedagem = Hospedagem.create! valid_attributes
      expect {
        delete :destroy, {:id => hospedagem.to_param}, valid_session
      }.to change(Hospedagem, :count).by(-1)
    end

    it "redirects to the hospedagens list" do
      hospedagem = Hospedagem.create! valid_attributes
      delete :destroy, {:id => hospedagem.to_param}, valid_session
      response.should redirect_to(hospedagens_url)
    end
  end

end
